name: Theme check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  theme-check:
    name: Shopify theme check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: shopify/theme-check-action@v2
        with:
          theme_root: '.'
          flags: '--fail-level error'
          token: ${{ github.token }}
